# Site settings
title: peterstace.github.io
email: peterstace@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog. It's main focus is on software engineering, computer science, and technology in general.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://peterstace.github.io" # the base hostname & protocol for your site
twitter_username: MrPeterStace
github_username:  peterstace

# Build settings
markdown: kramdown
