# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Ado"
license = "MIT"
licenselink = "https://github.com/peterstace/peterstace.github.io/blob/master/LICENSE.md"
description = "Simple theme for my personal blog"
homepage = "http://siteforthistheme.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
